name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      
      - name: Cache go module
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies and run test
        run: |
          go test ./...

      - name: Build
        env:
          NAME: clash
          BINDIR: bin
        run: make -j releases

      - name: Upload Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.Action_TOKEN }}
        with:
          files: bin/*
          draft: true
          prerelease: true
